---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: run & port mapping
    command: docker run --name myapp -d -p 8181:80 sonal04/ecomm20:image 







