---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: pull an image nginx
    command: docker pull nginx
  - name: pull edureka image
    command: docker pull devopsedu/webapp
  - name: run & port mapping
    command: docker run --name E1 -d -p 8181:80 devopsedu/webapp
    command: docker run --name N1 -d -p 8282:80 nginx






